mysql:
  dsn: ealert:123456@tcp(ecmdb-mysql:3306)/ealert?charset=utf8mb4&parseTime=True&loc=Local&timeout=5s

redis:
  addr: "ecmdb-redis:6379"
  password: "1234567890"
  db: 0

session:
  session_encrypted_key: "1234567890Key"
  cookie:
    domain: ".example.com"
    name: "ecmdb-token-key"

lark:
  app_id: ""
  app_secret: ""

email:
  smtp_host: "smtp.qq.com"
  smtp_port: 587
  smtp_username: "******@qq.com"
  smtp_password: "********"
  form_email: "********"@qq.com"
  form_name: "[告警通知] 测试告警"

pool:
  initGo: 1000
  coreGo: 1500
  maxGo: 2000
  maxIdleTime: 5000000000
  queueSize: 1000
  queueBacklogRate: 0.8

etcd:
  endpoints:
    - ecmdb-etcd:2379

grpc:
  server:
    ealert:
      name: "ealert"
      listen_addr: "0.0.0.0:7867"
      auth_token: "1234567890"
  client:
    ecmdb:
      name: "ecmdb"
      auth_token: "1234567890"